# -*- coding: utf-8 -*-
"""Data Science Process & Basics Pandas Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ejt4PXUmnkNdILAwhzWE2KbRHSRl-mfk

### Data Science

Data science is the process of using data to gain knowledge and make informed decisions. It involves collecting, cleaning, and analyzing data to uncover patterns, relationships, and insights.

###Data Science Process
* Data Collection

* Data Cleaning

* Feature Engineering

* Data Visualization

* Model Building

* Statistical Inference

* Error Dignoziation

* Dashboarding

###Data Cleaning
"""

import pandas as pd
df= pd.read_csv("https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv")
df

"""**By Using Pandas Function, you can easily understand the basic structure of your dataset**

What is the dataset about?

What is the shape of the dataset?

What are the names of the columns in the dataset?

What is the name and datatype of the target column in the dataset?

What are the data types of the features?

Are there any columns with null values in the dataset? If so, which columns contain null values and how many null values are present in each?

What is the range of values for each column?

#### Pandas Basic Function
"""

# Print Starting Five Rows of your Dataset
df.head()

# Print Last Five Rows of your Dataset
df.tail()

# Show a concise summary of the DataFrame.
# It includes the number of entries (rows), the number of non-null values in each column and their data types.
df.info()

# Generates descriptive statistics for numerical columns in the DataFrame.
# This includes metrics such as count, mean, standard deviation, minimum, maximum, and quartiles.
df.describe()

# The .columns attribute returns the column labels of the DataFrame as an Index object.
df.columns

# The .shape attribute returns a tuple representing the dimensions of the DataFrame.
# It provides the number of rows and columns in the format (number_of_rows, number_of_columns).
df.shape

